

export const categoryPath = [
    { name: 'Asian', url: 'Img/category-images/asianFusion.png' },
    { name: 'BBQ', url: 'Img/category-images/meatGrill.png' },
    { name: 'Pizza', url: 'Img/category-images/pizza.png' },
    { name: 'Burgers', url: 'Img/category-images/burgers.png' },
    { name: 'Sushi', url: 'Img/category-images/japaneseSushi.png' },
    { name: 'Salads', url: 'Img/category-images/salads.png' },
    { name: 'Coffee House', url: 'Img/category-images/coffeeHouse.png' },
    { name: 'Home Made', url: 'Img/category-images/homeMade.png' },
    { name: 'Pasta', url: 'Img/category-images/pasta.png' },
    { name: 'Fish', url: 'Img/category-images/fish.png' },
    { name: 'Humus', url: 'Img/category-images/humus.png' },
    { name: 'Gelato', url: 'Img/category-images/gelato.png' },
    { name: 'Wraps', url: 'Img/category-images/sandwichesWraps.png' },
    { name: 'Store', url: 'Img/category-images/convenienceStore.png' },
    { name: 'Patisserie', url: 'Img/category-images/patisserie.png' },
    { name: 'Juice', url: 'Img/category-images/SmoothiesAndShakes.png' },
    { name: 'Mexican', url: 'Img/category-images/mexican.png' },
    { name: 'Indian', url: 'Img/category-images/indian.png' },
    { name: 'Falafel', url: 'Img/category-images/falafel.png' },
    { name: 'Seafood', url: 'Img/category-images/seafood.png' },
    { name: 'Poke', url: 'Img/category-images/poke.png' },
    { name: 'Soup', url: 'Img/category-images/soup.png' },
    { name: 'Pastries', url: 'Img/category-images/bakery.png' },
    { name: 'Bar', url: 'Img/category-images/bar.png' },
    { name: 'Home cooks', url: 'Img/category-images/homecooked.png' },
    { name: 'Fresh fish', url: 'Img/category-images/freshfish.png' },
    { name: 'Liquid store', url: 'Img/category-images/alcoholic.png' },
    { name: 'Cheese shop', url: 'Img/category-images/cheeseshop.png' },
    { name: 'Fruits & Veg', url: 'Img/category-images/fruitsAndVeg.png' },
    { name: 'Fruit trays', url: 'Img/category-images/fruitplatters.png' },
    { name: 'Delicatessen', url: 'Img/category-images/delicatessen.png' },
    { name: 'Sweets', url: 'Img/category-images/sweetsAndTreats.png' },
    { name: 'Butcher', url: 'Img/category-images/butcher.png' },
]